-- Inserir Clientes
INSERT INTO TB_CLIENT (NAME, CPF, INCOME, SEXO, EMAIL, BIRTH_DATE, SENHA, FOTO) VALUES ('JOSE EUSTAQUIO', '936.909.604-36', 1600.0, 'M', 'jose@exemplo.com', TIMESTAMP WITH TIME ZONE '1985-01-10T20:50:07.12345Z', '$2a$10$kPx82QLFNPT2ncXlhm4hiOKkUrQ.b13ziLv1Dx6kXiUSmul/n7jyy', ''); -- https://drive.google.com/uc?export=download&id=1zPBq8kemle5Q2vQxMty-IKSaPzug20Sk
INSERT INTO TB_CLIENT (NAME, CPF, INCOME, SEXO, EMAIL, BIRTH_DATE, SENHA, FOTO) VALUES ('ROSE ROZINHA', '101.792.324-87', 2100.0, 'M', 'rosekenga@exemplo.com', TIMESTAMP WITH TIME ZONE '1993-02-20T10:25:04.12345Z', '$2a$10$pbAURjWKCIcD/QNq6kskhOO1o2O0ALb3TYiZsENPpp/D/5xocuQ5a', ''); --https://drive.google.com/uc?export=download&id=1BvK5YZyZf1NIQhgUp4Lw_hD06vP3aMBV
INSERT INTO TB_CLIENT (NAME, CPF, INCOME, SEXO, EMAIL, BIRTH_DATE, SENHA, FOTO) VALUES ('ANA CASTELLA', '613.173.528-07', 1900.5, 'F', 'ana@exemplo.com', TIMESTAMP WITH TIME ZONE '2000-03-15T15:36:00.12345Z', '$2a$10$qGMvT3AvtGNJeZEhCEkkSuHQ3iXRkLlIxcdifuP918K0aXK243Bla', '');
INSERT INTO TB_CLIENT (NAME, CPF, INCOME, SEXO, EMAIL, BIRTH_DATE, SENHA, FOTO) VALUES ('ARLETE SOUZA', '962.641.291-78', 2300, 'F', 'arlete@exemplo.com', TIMESTAMP WITH TIME ZONE '1993-04-30T20:08:35.12345Z', '$2a$10$qGMvT3AvtGNJeZEhCEkkSuHQ3iXRkLlIxcdifuP918K0aXK243Bla', '');
INSERT INTO TB_CLIENT (NAME, CPF, INCOME, SEXO, EMAIL, BIRTH_DATE, SENHA, FOTO) VALUES ('KIKO RODRIGUES', '846.970.801-57', 3800, 'M', 'kiko@exemplo.com', TIMESTAMP WITH TIME ZONE '1990-05-17T20:50:07.12345Z', '$2a$10$qGMvT3AvtGNJeZEhCEkkSuHQ3iXRkLlIxcdifuP918K0aXK243Bla', '');
INSERT INTO TB_CLIENT (NAME, CPF, INCOME, SEXO, EMAIL, BIRTH_DATE, SENHA, FOTO) VALUES ('SHELDON BAVARIO', '925.235.732-70', 2540.0, 'M', 'sheldon@exemplo.com', TIMESTAMP WITH TIME ZONE '1999-06-16T07:37:07.12345Z', '$2a$10$qGMvT3AvtGNJeZEhCEkkSuHQ3iXRkLlIxcdifuP918K0aXK243Bla', '');
INSERT INTO TB_CLIENT (NAME, CPF, INCOME, SEXO, EMAIL, BIRTH_DATE, SENHA, FOTO) VALUES ('DIMA SHEYLLA', '974.647.305-00', 1980.5, 'F', 'dima@exemplo.com', TIMESTAMP WITH TIME ZONE '1989-07-19T10:20:09.12345Z', '$2a$10$qGMvT3AvtGNJeZEhCEkkSuHQ3iXRkLlIxcdifuP918K0aXK243Bla', '');
INSERT INTO TB_CLIENT (NAME, CPF, INCOME, SEXO, EMAIL, BIRTH_DATE, SENHA, FOTO) VALUES ('ASTROGILDO MAGALHAES', '986.220.151-73', 2700.0, 'M', 'astro@exemplo.com', TIMESTAMP WITH TIME ZONE '1995-08-24T23:55:17.12345Z', '$2a$10$qGMvT3AvtGNJeZEhCEkkSuHQ3iXRkLlIxcdifuP918K0aXK243Bla', '');
INSERT INTO TB_CLIENT (NAME, CPF, INCOME, SEXO, EMAIL, BIRTH_DATE, SENHA, FOTO) VALUES ('ROBERTO MOTA', '207.809.597-44', 2980.0, 'M', 'roberto@exemplo.com', TIMESTAMP WITH TIME ZONE '1988-09-19T21:18:15.12345Z', '$2a$10$qGMvT3AvtGNJeZEhCEkkSuHQ3iXRkLlIxcdifuP918K0aXK243Bla', '');
INSERT INTO TB_CLIENT (NAME, CPF, INCOME, SEXO, EMAIL, BIRTH_DATE, SENHA, FOTO) VALUES ('ANACLECIA ALMEIDA', '130.753.592-54', 3000.0, 'F', 'clecia@exemplo.com', TIMESTAMP WITH TIME ZONE '1994-10-13T17:34:04.12345Z', '$2a$10$qGMvT3AvtGNJeZEhCEkkSuHQ3iXRkLlIxcdifuP918K0aXK243Bla', '');
INSERT INTO TB_CLIENT (NAME, CPF, INCOME, SEXO, EMAIL, BIRTH_DATE, SENHA, FOTO) VALUES ('GLANDULA PTUITARIA', '242.601.400-86', 3564.00, 'M', 'gland@exemplo.com', TIMESTAMP WITH TIME ZONE '1988-06-19T10:19:08.12345Z', '$2a$10$qGMvT3AvtGNJeZEhCEkkSuHQ3iXRkLlIxcdifuP918K0aXK243Bla', '');

-- Inserir endereços
INSERT INTO TB_ENDERECOS (RUA, BAIRRO, NUM, CIDADE, ESTADO, COUNTRY, CEP, CLIENT_ID) VALUES ('Rua A', 'Bairro A', 100, 'Cidade A', 'Estado A', 'Brasil', '00000-000', 1);
INSERT INTO TB_ENDERECOS (RUA, BAIRRO, NUM, CIDADE, ESTADO, COUNTRY, CEP, CLIENT_ID) VALUES ('Rua B', 'Bairro B', 200, 'Cidade B','Estado B', 'Brasil', '11111-111', 1);
INSERT INTO TB_ENDERECOS (RUA, BAIRRO, NUM, CIDADE, ESTADO, COUNTRY, CEP, CLIENT_ID) VALUES ('Rua C', 'Bairro C', 300, 'Cidade C','Estado C', 'Estados Unidos', '22222-222', 2);
INSERT INTO TB_ENDERECOS (RUA, BAIRRO, NUM, CIDADE, ESTADO, COUNTRY, CEP, CLIENT_ID) VALUES ('Rua D', 'Bairro D', 400, 'Cidade D','Estado D', 'Canadá', '33333-333', 3);
INSERT INTO TB_ENDERECOS (RUA, BAIRRO, NUM, CIDADE, ESTADO, COUNTRY, CEP, CLIENT_ID) VALUES ('Rua E', 'Bairro E', 500, 'Cidade E','Estado E', 'Alemanha', '44444-444', 4);
INSERT INTO TB_ENDERECOS (RUA, BAIRRO, NUM, CIDADE, ESTADO, COUNTRY, CEP, CLIENT_ID) VALUES ('Rua F', 'Bairro F', 600, 'Cidade F','Estado F', 'França', '55555-555', 5);
INSERT INTO TB_ENDERECOS (RUA, BAIRRO, NUM, CIDADE, ESTADO, COUNTRY, CEP, CLIENT_ID) VALUES ('Rua G', 'Bairro G', 700, 'Cidade G','Estado G', 'Japão', '66666-666', 6);
INSERT INTO TB_ENDERECOS (RUA, BAIRRO, NUM, CIDADE, ESTADO, COUNTRY, CEP, CLIENT_ID) VALUES ('Rua H', 'Bairro H', 800, 'Cidade H','Estado H', 'Brasil', '77777-777', 7);
INSERT INTO TB_ENDERECOS (RUA, BAIRRO, NUM, CIDADE, ESTADO, COUNTRY, CEP, CLIENT_ID) VALUES ('Rua I', 'Bairro I', 900, 'Cidade I','Estado I', 'Estados Unidos', '88888-888', 8);
INSERT INTO TB_ENDERECOS (RUA, BAIRRO, NUM, CIDADE, ESTADO, COUNTRY, CEP, CLIENT_ID) VALUES ('Rua J', 'Bairro J', 1000, 'Cidade J','Estado J', 'Canadá', '99999-999', 9);
INSERT INTO TB_ENDERECOS (RUA, BAIRRO, NUM, CIDADE, ESTADO, COUNTRY, CEP, CLIENT_ID) VALUES ('Rua K', 'Bairro K', 1100, 'Cidade K','Estado K', 'Alemanha', '10100-100', 10);
INSERT INTO TB_ENDERECOS (RUA, BAIRRO, NUM, CIDADE, ESTADO, COUNTRY, CEP, CLIENT_ID) VALUES ('Rua L', 'Bairro L', 1200, 'Cidade L','Estado L', 'Japão', '10101-101', 11);
INSERT INTO TB_ENDERECOS (RUA, BAIRRO, NUM, CIDADE, ESTADO, COUNTRY, CEP, CLIENT_ID) VALUES ('Rua M', 'Bairro M', 1300, 'Cidade M','Estado M', 'Japão', '10102-102', 11);

-- Inserir telefones P= PESSOAL T= PROFISSIONAL C= COMERCIAL R= RESIDENCIAL
INSERT INTO TB_CELLPHONE (DDD, NUMBER, TIPO, CLIENT_ID) VALUES (81, '9 1111-1111', 'P', 1);
INSERT INTO TB_CELLPHONE (DDD, NUMBER, TIPO, CLIENT_ID) VALUES (82, '9 2222-2222', 'T', 1);
INSERT INTO TB_CELLPHONE (DDD, NUMBER, TIPO, CLIENT_ID) VALUES (83, '9 3333-3333', 'P', 2);
INSERT INTO TB_CELLPHONE (DDD, NUMBER, TIPO, CLIENT_ID) VALUES (84, '9 4444-4444', 'C', 2);
INSERT INTO TB_CELLPHONE (DDD, NUMBER, TIPO, CLIENT_ID) VALUES (85, '9 5555-5555', 'C', 3);
INSERT INTO TB_CELLPHONE (DDD, NUMBER, TIPO, CLIENT_ID) VALUES (86, '9 6666-6666', 'R', 4);
INSERT INTO TB_CELLPHONE (DDD, NUMBER, TIPO, CLIENT_ID) VALUES (87, '9 7777-7777', 'T', 5);
INSERT INTO TB_CELLPHONE (DDD, NUMBER, TIPO, CLIENT_ID) VALUES (88, '9 8888-8888', 'C', 6);

-- Inserir Categoria de clientes
INSERT INTO TB_CATEGORY_CLIENT (DESCRIPTION) VALUES ('PAGA EM DIA');
INSERT INTO TB_CATEGORY_CLIENT (DESCRIPTION) VALUES ('ATRASA PAGAMENTO');
INSERT INTO TB_CATEGORY_CLIENT (DESCRIPTION) VALUES ('MAIS DE 1 ANO');
INSERT INTO TB_CATEGORY_CLIENT (DESCRIPTION) VALUES ('MENOS DE 1 ANO');
INSERT INTO TB_CATEGORY_CLIENT (DESCRIPTION) VALUES ('RUIM');
INSERT INTO TB_CATEGORY_CLIENT (DESCRIPTION) VALUES ('BOM');
INSERT INTO TB_CATEGORY_CLIENT (DESCRIPTION) VALUES ('MARROMENOS');

-- Vincular categoria a cliente
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (1,2);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (1,3);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (1,5);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (2,1);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (2,4);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (3,1);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (3,3);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (3,6);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (4,2);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (5,6);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (6,1);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (6,3);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (6,5);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (7,1);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (7,4);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (7,5);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (8,4);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (8,5);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (9,4);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (10,2);
INSERT INTO TB_CLIENT_CATEGORY (CLIENT_ID, CATEGORYCLIENT_ID) VALUES (11,1);

-- Inserir usuarios
INSERT INTO TB_USER (NOME, SOBRENOME, SENHA, EMAIL, IDADE, FOTO, DT_NASCIMENTO, CREATE_AT, UPDATE_AT, ACCOUNT_BLOK)
VALUES ('ADSON', 'FARIAS', '$2a$10$on5XZrC87ppA/cozWviTe.aKMK2bXDPLnozamMBxolXOdmdhbk7uC', 'ADSON@EXEMPLO.COM.BR', 33, '', '1990-11-12', '2024-05-16 17:50:00', NULL, FALSE);
INSERT INTO TB_USER (NOME, SOBRENOME, SENHA, EMAIL, IDADE, FOTO, DT_NASCIMENTO, CREATE_AT, UPDATE_AT, ACCOUNT_BLOK)
VALUES ('LUIZ','JANUARIO','$2a$10$ChDa4UckO/93mN.PpVjv3.UCt7dsNl7nxmqqWm8AaSRgf2RTVcWY6','LUIZ@EXEMPLO.COM.BR',44,'','1980-05-10','2024-05-16 17:50:00', NULL, TRUE);
INSERT INTO TB_USER (NOME, SOBRENOME, SENHA, EMAIL, IDADE, FOTO, DT_NASCIMENTO, CREATE_AT, UPDATE_AT, ACCOUNT_BLOK)
VALUES ('VALERIA','SILVA','$2a$10$xhz7uIMiy.rroa9Gc5uPq.J3EzBEIrSTS8jrMsDPfXLx0G97YDG8O','VALERIA@EXEMPLO.COM.BR',34,'','1988-07-15','2024-05-16 17:50:00',NULL, FALSE);

-- inserir roles
INSERT INTO TB_ROLES (AUTHORITY) VALUES ('GERENTE');
INSERT INTO TB_ROLES (AUTHORITY) VALUES ('SUPERVISOR');
INSERT INTO TB_ROLES (AUTHORITY) VALUES ('PEÃO');
INSERT INTO TB_ROLES (AUTHORITY) VALUES ('BASIC');

-- vincular roles a usuarios
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) VALUES (2,3);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) VALUES (3,2);

-- Inserir produtos
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('PS4', 4250.00, '','PLAY STATION GEN4', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('NOTBOOK LEN', 3850.80, '','NOTBOOK LENOVO GEN5', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('XIAOMI 13T', 4500.00, '','CELULAR XIAOMI 13T MIUI 14', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('XIAOMI NOTE12', 1500.00, '','CELULAR XIAOMI NOTE12 256GB 8GB', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('SAMSUNG A30', 1870.00, '','CELL SAMSUNG A30 PRETO', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('MOTO G5', 2640.40, '','CELULAR MOTOROLA G5', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('XBOX', 4900.00, '','X-BOX ONE', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('NOTE GAMER ACER', 5150.89, '','NOTEBOOK ACER NITRO 5 GAMER', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('LIVRO JSE SARAMAGO', 45.00, '','ENSAIO SOBRE A CEGUEIRA', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('LIVRO JSE SARAMAGO', 47.00, '','ENSAIO SOBRE A LUCIDEZ', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('LIVRO 2WW', 39.00, '','STALIN, OS NAZISTAS E O OCIDENTE', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('JHONNY WALKER', 89.00, '','RED LABEL J. WALKER 750ML', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('JHONNY WALKER', 129.00, '','BLACK LABEL J. WALKER 1L', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('JHONNY WALKER', 600.00, '','BLUE LABEL J. WALKER 1L', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('JHONNY WALKER', 479.00, '','GREEN LABEL J. WALKER 750ML', '2024-05-17 20:44:00');
INSERT INTO TB_PRODUCT (NAME,PRICE,IMG_URL,DESCRIPTION,DT_INCLUDED) 
VALUES ('WHITE HORSE', 109.00, '','WHISKY WHITE HORSE 1L', '2024-05-17 20:44:00');

-- Inserir categoria de produtos
INSERT INTO TB_CATEGORY_PRODUCT (DESCRIPTION) VALUES ('ELETRONICOS');
INSERT INTO TB_CATEGORY_PRODUCT (DESCRIPTION) VALUES ('LIVROS');
INSERT INTO TB_CATEGORY_PRODUCT (DESCRIPTION) VALUES ('BEBIDAS');
INSERT INTO TB_CATEGORY_PRODUCT (DESCRIPTION) VALUES ('CELULAR');
INSERT INTO TB_CATEGORY_PRODUCT (DESCRIPTION) VALUES ('NOTEBOOK');
INSERT INTO TB_CATEGORY_PRODUCT (DESCRIPTION) VALUES ('GAMER');
INSERT INTO TB_CATEGORY_PRODUCT (DESCRIPTION) VALUES ('AUTO AJUDA');
INSERT INTO TB_CATEGORY_PRODUCT (DESCRIPTION) VALUES ('HISTÓRIA');
INSERT INTO TB_CATEGORY_PRODUCT (DESCRIPTION) VALUES ('1L');
INSERT INTO TB_CATEGORY_PRODUCT (DESCRIPTION) VALUES ('750ML');
INSERT INTO TB_CATEGORY_PRODUCT (DESCRIPTION) VALUES ('FAMILIA JHONNY WALKER');
INSERT INTO TB_CATEGORY_PRODUCT (DESCRIPTION) VALUES ('CONSOLE');

-- Vincular categoria a produto
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (1,12);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (2,1);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (2,5);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (3,1);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (3,4);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (3,6);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (4,1);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (4,4);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (5,1);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (5,4);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (6,1);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (6,4);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (7,1);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (7,6);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (7,12);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (8,1);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (8,5);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (8,6);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (9,2);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (9,7);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (10,2);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (10,7);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (11,2);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (11,8);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (12,3);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (12,10);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (12,11);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (13,3);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (13,9);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (13,11);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (14,3);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (14,9);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (14,11);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (15,3);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (15,10);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (15,11);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (16,3);
INSERT INTO TB_PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_PRODUCT_ID) VALUES (16,9);


-- Compras
INSERT INTO TB_COMPRAS (COD_CLI, DATA_COMPRA) 
VALUES (1, TIMESTAMP WITH TIME ZONE '2024-01-10');
INSERT INTO TB_COMPRAS (COD_CLI, DATA_COMPRA) 
VALUES (1, TIMESTAMP WITH TIME ZONE '2024-01-12');
INSERT INTO TB_COMPRAS (COD_CLI, DATA_COMPRA) 
VALUES (2, TIMESTAMP WITH TIME ZONE '2024-01-25');
INSERT INTO TB_COMPRAS (COD_CLI, DATA_COMPRA) 
VALUES (3, TIMESTAMP WITH TIME ZONE '2024-02-05');
INSERT INTO TB_COMPRAS (COD_CLI, DATA_COMPRA) 
VALUES (4, TIMESTAMP WITH TIME ZONE '2024-03-01');

-- Compras x itens da compra
INSERT INTO TB_COMPRAS_ITENS (COMPRA_ID, PRODUTO_ID, QUANTIDADE, PRECO, CATEGORIA_ID)
VALUES 
    (1, 2, 1, 3850.00, 1),
    (1, 3, 2, 4500.00, 1),
    (1, 4, 3, 1500.00, 1);
INSERT INTO TB_COMPRAS_ITENS (COMPRA_ID, PRODUTO_ID, QUANTIDADE, PRECO, CATEGORIA_ID)
VALUES 
    (2, 2, 3, 3850.80, 5),
    (2, 6, 2, 2640.40, 4);  
INSERT INTO TB_COMPRAS_ITENS (COMPRA_ID, PRODUTO_ID, QUANTIDADE, PRECO, CATEGORIA_ID)
VALUES 
	(3, 10, 5, 47.00, 2),
	(3, 11, 6, 39.00, 2);
INSERT INTO TB_COMPRAS_ITENS (COMPRA_ID, PRODUTO_ID, QUANTIDADE, PRECO, CATEGORIA_ID)
VALUES
	(4, 14, 1, 600.00, 3);
INSERT INTO TB_COMPRAS_ITENS (COMPRA_ID, PRODUTO_ID, QUANTIDADE, PRECO, CATEGORIA_ID)
VALUES
	(5, 5, 2, 1870.00, 4);		












    
